# fly.toml app configuration file generated for discord-role-bot-main on 2024-11-13T01:41:50Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'discord-role-bot-main'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
